### ISSUE TITLE
1 minute delay on exit

### ISSUE THREAD

**Issue by metametadata** [nrepl/nrepl#219] opened 2020-12-15 17:45 UTC
## Expected behavior

There's no delay on exit.

## Actual behavior

App waits for 1 minute before exiting.

## Steps to reproduce the problem

Require `nrepl.server` ns and exit the app. Example for version `0.8.0`:

```
$ time clj -Sdeps '{:deps {nrepl {:mvn/version "0.8.0"}}}' -e "(do (require 'nrepl.server) (prn :hi))"
:hi
clj -Sdeps '{:deps {nrepl {:mvn/version "0.8.0"}}}' -e   5.89s user 0.39s system 10% cpu 1:01.57 total
```

## Other

The issue is not reproducible in `0.7.0`:
```
$ time clj -Sdeps '{:deps {nrepl {:mvn/version "0.7.0"}}}' -e "(do (require 'nrepl.server) (prn :hi))"
:hi
clj -Sdeps '{:deps {nrepl {:mvn/version "0.7.0"}}}' -e   5.06s user 0.32s system 344% cpu 1.563 total
```

### Clojure version

1.10.1

### Java version

11.0.9

### Operating system

macOS

**Comment by bbatsov** [comment] 2021-07-29 05:32
Is this still slow with the latest beta?

**Comment by metametadata** [comment] 2021-07-29 10:47
Yes.

```
$ time clj -Sdeps '{:deps {nrepl {:mvn/version "0.9.0-beta1"}}}' -e "(do (require 'nrepl.server) (prn :hi))"
:hi
clj -Sdeps '{:deps {nrepl {:mvn/version "0.9.0-beta1"}}}' -e   5.38s user 0.40s system 9% cpu 1:01.74 total
```

**Comment by bbatsov** [comment] 2021-08-18 08:09
Hmm, I can't put my finger on which particular change in 0.8 caused this regression. We might have to bisect the code to figure this out, or profile that `require`, as I assume it's triggering something that takes a while now. 

@shen-tian any ideas what might be causing this?

**Comment by shen-tian** [comment] 2021-08-20 08:45
Sorry I've been awol. I just had a look through changelog, and nothing jumps out at me. The exactly 1 minute part is also curious. The only thing close I can think of is https://github.com/nrepl/nrepl/pull/163 <- but that's before 0.8.

**Comment by metametadata** [comment] 2021-08-20 11:13
1 minute delay looks like a problem related to agent pool.  Maybe `future`, `pmap` or `agent-send` were added after v0.7.0. See https://clojure.atlassian.net/browse/CLJ-124.

If it's true and nREPL cannot be fixed then all the consumers may need to add `shutdown-agents` calls as recommended in https://clojure.org/guides/faq#agent_shutdown: 

>  When a program like this finishes, there will be a 60 second pause before exit. To fix this problem, call shutdown-agents as the program exits.

The discussion about a similar problem in `clojure.java.shell/sh`: https://clojureverse.org/t/why-doesnt-my-program-exit/3754.

**Comment by alexander-yakushev** [comment] 2024-07-18 08:51
Since after #345 we don't touch futures anymore in nREPL, this should be fixed.

**Closed by alexander-yakushev** 2024-07-18 08:51 UTC
Labels: Bug
