### ISSUE TITLE
Qualified keywords are always in user namespace

### ISSUE THREAD

**Issue by konstlepa** [nrepl/nrepl#208] opened 2020-08-27 14:55 UTC
Hello,

I have a problem with qualified keywords in nrepl. All qualified keywords resolve as **:user/\<keyword\>** . There is no such problem in other repls (I checked clj repl, org.clojure/tools.nrepl, REPL-y and so on).

## Expected behavior
```
$ clj -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"}}}'
Clojure 1.10.1
user=> ::a
:user/a
user=> (ns myns)
nil
myns=> ::a
:myns/a
myns=>
```

## Actual behavior
```
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.0"}}}' -m nrepl.cmdline --interactive
nREPL server started on port 54197 on host localhost - nrepl://localhost:54197
nREPL 0.8.0
Clojure 1.10.1
OpenJDK 64-Bit Server VM 11.0.8+10
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> ::a
:user/a
user=> (ns myns)
nil
myns=> ::a
:user/a
myns=>
```

### Clojure version

1.10.1.561

### Java version

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### Operating system

macOS Catalina 10.15.5

**Comment by bbatsov** [comment] 2020-09-16 05:05
> There is no such problem in other repls (I checked clj repl, org.clojure/tools.nrepl, REPL-y and so on).

That's some bug in the cmdline interface, as it works fine with REPL-y or CIDER. Probably it's an easy fix. @shen-tian any ideas what might be causing this? I assume we're not tracking the properly the ns somewhere.

**Comment by shen-tian** [comment] 2020-09-18 14:22
My guess is that it's a built-in client issue?

Also, just to point out, the "Expected behavior" command doesn't actually use nREPL.

**Comment by bbatsov** [comment] 2020-09-22 05:29
> Also, just to point out, the "Expected behavior" command doesn't actually use nREPL.

Great point! I had even forgotten there used to be a `main` there. :-)

**Comment by jqmtor** [comment] 2021-04-18 15:43
I replicated this issue in a test [here](https://github.com/nrepl/nrepl/compare/master...jqmtor:208/client/fix-auto-resolved-keywords?expand=1) and, curiously, it seems like the client is doing the right thing? 

I followed on your suspicion that the client does not keep track of the namespace properly, but that seems to be correct.

I also wondered whether the issue could be with the keyword being resolved at read time, but the test above seems to rule that out. I am probably missing something relevant, but I am happy to follow up on this.

**Comment by mikemar10** [comment] 2021-07-11 04:56
I took some time to dig into this issue and it appears to have been due to the way the namespaces were being kept in sync between `nrepl.cmdline/run-repl` and the nrepl server. This was being handled by tracking namespace changes in an atom client side, but this causes namespace resolution to always resolve to the `user` namespace on the client side since the client side namespace isn't actually changing. The cmdline uses `clojure.core/read` to fetch input which performs namespace resolution on the client side in the `user` namespace before sending the resolved input to the server. I've PR #239  that resolves this problem by rebinding `*ns*` on the client side to reflect the namespace the server is currently in.

Incidentally, this means that the cmdline repl namespace resolution was broken for all forms of namespace resolution, not just qualified keywords.

I also took a look at the test that @jqmtor provided but there is a bug in that test, the client sends two messages to the server but the messages are sent in separate sessions which is why the test fails. When the test is updated to use the same session it passes as expected. 

This issue was only in the input processing of the main loop of `nrepl.cmdline/run-repl` as far as I can tell and didn't otherwise impact the nrepl client or server code.

I'm relatively new to clojure so please let me know if there is anything wrong with the proposed fix. Any and all criticism is very much appreciated. Thank you very much for taking the time to tag some issues as beginner friendly!

**Closed** 2021-07-29 05:14 UTC
Labels: Bug, Good First Issue
