### ISSUE TITLE
*print-namespace-maps* is always true

### ISSUE THREAD

**Issue by Reefersleep** [nrepl/nrepl#33] opened 2018-06-03 18:53 UTC
## Expected behavior, actual behavior and steps to reproduce the problem

Evaluating a map with namespaced keys like
`{:person/name "Fred" :person/age 50}`
in the cider repl prints the following return value
`#:person{:name "Fred", :age 50}`
This is due to `*print-namespace-maps*` defaulting to `true`.
Normally, it should be possible to change the value of this var permanently with `set!` thusly:
```
user> (set! *print-namespace-maps* false)
false
user> *print-namespace-maps*
false
```
However, the actual behavior is thus:
```
user> (set! *print-namespace-maps* false)
false
user> *print-namespace-maps*
true
```
Similarly, it should be possible to temporarily change the var with `binding`:
```
user> (binding [*print-namespace-maps* false]
        [*print-namespace-maps* {:person/name "Fred" :person/age 50}])
[false {:person/name "Fred" :person/age 50}]
```
But, although the var seems to change, the desired behavior remains to be seen;
```
user> (binding [*print-namespace-maps* false]
        [*print-namespace-maps* {:person/name "Fred" :person/age 50}])
[false #:person{:name "Fred", :age 50}]
```

I first posted this problem as an issue at the CIDER repo: https://github.com/clojure-emacs/cider/issues/2280 
@bbatsov pointed out that it must be a problem in nrepl, so I reposted the issue here and closed the original issue.
Some of the discussion in the thread underneath the original issue might prove useful. 

Following the issue instructions there, I included information about my CIDER version, emacs version and operating system. I'll include them here, as well;
 
### CIDER version information

```
;; CIDER 0.15.0 (London), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_92
```

### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, NS apple-appkit-1404.34) of 2016-06-01

### Operating system

OSX El Capitan, Version 10.11.6

**Comment by arrdem** [comment] 2018-06-05 03:54
The root cause here is almost certainly that middlewares are NOT executed using the same dynamic var / session bindings as user request code. This also dovetails into larger considerations of how using middlewares to render results given the current architecture isn't really disciplined or composable and may be worth revisiting.

**Comment by dchelimsky** [comment] 2018-06-06 11:53
As @Reefersleep points out:

```
user> (binding [*print-namespace-maps* false]
        [*print-namespace-maps* {:person/name "Fred" :person/age 50}])
[false #:person{:name "Fred", :age 50}]
```

However, `pprint` seems to work differently.

```
user> (clojure.pprint/pprint {:person/name "Fred" :person/age 50})
#:person{:name "Fred", :age 50}
nil
user> (binding [*print-namespace-maps* false]
       (clojure.pprint/pprint
        [*print-namespace-maps* {:person/name "Fred" :person/age 50}]))
[false {:person/name "Fred", :person/age 50}]
nil
```

Note that `*print-namespace-maps*` still evals to `false`, but the map is printed without the namespace map format!

**Comment by arrdem** [comment] 2018-06-07 20:15
@Dirklectisch right - that's precisely the behavior I'm referring to.

In the first case, the expression `[*print-namespace-maps* {:person/name "Fred" :person/age 50}]` is evaluated in the context of `[*print-namespace-maps* false]`. It's just data, so the resulting value is returned as the result of the nREPL interruptible eval operation. The interruptible eval op pops and saves dynamic var bindings. Then /something/ (middleware) renders the value `[true {:person/name "Fred" :person/age 50}]` to a string. Since `*print-namespace-maps*` has already been popped, whatever the parent binding (`true` presumably) is will be in effect which means that the string `"[false #:person{:name \"Fred\", :age 50}]"` is produced.

The `pprint` example you present "works differently" because the value `[false {:person/name "Fred", :person/age 50}]` is pretty printed while bindings are in effect, and becomes nREPL `out` messages along with the `eval` result of `nil` all before the interruptible eval op finishes and pops bindings.

**Comment by cursive-ide** [comment] 2018-07-01 00:02
BTW I wrote about this problem over on the Cursive issue tracker at cursive-ide/cursive#1541.

**Comment by bbatsov** [comment] 2018-07-13 16:14
I can take a look at this after https://github.com/technomancy/leiningen/pull/2444 gets merged, but for the time being my focus is getting the updated nREPL into the hands of users. 

If someone wants to tackle this in the mean time - be my guest. :-)

**Comment by bbatsov** [comment] 2018-07-23 10:14
Btw, @greglook, I noticed you filed the original ticket. Are you interested in working on making this customisable?

**Comment by bbatsov** [comment] 2018-10-18 18:11
@mallt Yep, this seems like a reasonable solution to me. 

How you testing this, btw?

**Comment by bbatsov** [comment] 2018-10-18 18:34
I've documented a bit of this https://nrepl.xyz/nrepl/0.4.5/hacking_on_nrepl.html

Might be a good idea to extend the hacking sections with tips on interactive developing nREPL.

**Comment by mallt** [comment] 2018-10-18 21:46
The proposed solution seems to work for clojure 1.9, but the tests for 1.7 and 1.8 fail on it because `*print-namespace-maps*` does not exist in these versions. 

I tried to wrap the `set!` in a `when`:
```clojure
(when (resolve '*print-namespace-maps*)
  (set! *print-namespace-maps* (@bindings #'*print-namespace-maps*)))
```
but this still throws a the error `Unable to resolve symbol: *print-namespace-maps* in this context`. 

I also tried like this:
```clojure
(when (resolve '*print-namespace-maps*)
  (set! (resolve '*print-namespace-maps*) (@bindings #'*print-namespace-maps*)))
```
but then I get a `Invalid assignment target` error.

Does anyone know if there's a way to make this work in clojure 1.7 and 1.8? Thanks!

**Comment by bbatsov** [comment] 2018-10-19 08:37
I'm not an expert on the subject, but it seems to me that we just need to define the dynamic var if it doesn't exist. Here's the definition in 1.9 - just a regular dynamic var. 

```
def ^:dynamic
 ^{:doc "*print-namespace-maps* controls whether the printer will print
  namespace map literal syntax. It defaults to false, but the REPL binds
  to true."
   :added "1.9"}
 *print-namespace-maps* false)
```

There's nothing magic about it. I guess you can conditionally define it when it's not present. Maybe @arrdem, @SevereOverfl0w or @puredanger would have a better idea, as I almost never use dynamic vars.

**Comment by mallt** [comment] 2018-10-19 09:46
Thanks @bbatsov! Adding the dynamic var like this fixes the tests for 1.7 and 1.8:
```clojure
(when-not (resolve 'clojure.core/*print-namespace-maps*)
  (def ^:dynamic *print-namespace-maps*
    "Define the var for clojure versions below 1.9"
    nil))
```

But the `when-not` doesn't seem to work in 1.9, causing the warning:

 `WARNING: *print-namespace-maps* already refers to: #'clojure.core/*print-namespace-maps* in namespace: nrepl.middleware.interruptible-eval, being replaced by: #'nrepl.middleware.interruptible-eval/*print-namespace-maps*`

when running the tests for 1.9.

The conditional definition does not seem to work for some reason, but I can't figure out why. Is there another way to achieve this conditional definition? Thanks!

**Comment by puredanger** [comment] 2018-10-19 13:44
You can use `(:refer-clojure :exclude [*print-namespace-maps*])` in your namespace declaration.

**Comment by puredanger** [comment] 2018-10-19 15:30
Can you just call clojure.main/with-bindings? The intent of that is to install the macro bindings needed at the repl. If you call that for whatever version of Clojure you are on, you should get the bindings that clojure.main provides.

**Comment by mallt** [comment] 2018-10-20 12:56
Thank you for the feedback @puredanger!

When switching to `clojure.main/with-bindings` locally, it seems the `*print-namespace-maps*` still needs to be set! explicitly in the :init of `clojure.main/repl`, otherwise changes to the var do not seem to come through (the same is currently done for *compile-path*, *1, *2, *3 and *e: https://github.com/nrepl/nREPL/blob/master/src/clojure/nrepl/middleware/interruptible_eval.clj#L92).

**Comment by bbatsov** [comment] 2018-10-20 13:13
@puredanger We're already using `with-bindings` https://github.com/nrepl/nREPL/blob/19868816a89878f9fc4caf8b08e7ac0bd8c65275/src/clojure/nrepl/middleware/session.clj#L117 (this wraps each evaluation)

I think this comment (https://github.com/nrepl/nREPL/blob/19868816a89878f9fc4caf8b08e7ac0bd8c65275/src/clojure/nrepl/middleware/interruptible_eval.clj#L91) is the key to our current problems and the need for some explicitly bindings to be re-established, but I'm not familiar with the implementation of `clojure.main/repl` to suggest an alternative approach to those extra bindings we do today manually. Hopefully the you can shed some light on this.

**Comment by bbatsov** [comment] 2018-10-24 17:03
@mallt Another potential solution was presented [here](https://stackoverflow.com/questions/52964622/bind-conditionally-a-dynamic-var-from-clojures-core-for-backwards-compatibility/52968638#52968638):

```clj
(defmacro def-dynamic-when-not-resolve [sym value]
  (when-not (resolve sym)
    `(def ~(vary-meta sym assoc :dynamic true) ~value)))
```

Can you test if this gets the job done?

**Closed** 2018-10-25 20:46 UTC
Labels: Enhancement, Good First Issue
